# Install the apt prerequisites
#language: go

#go:
#  - master # This uses automatically the latest version of go
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq hugo

#install:
#  - apt install hugo
#  - go get github.com/spf13/hugo # This provides the latest version of Hugo to Travis CI

script:
  - hugo

    # Deploy to GitHub pages
deploy:
  provider: pages
  target_branch: master
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  repo: opentechinstitute/opentechinstitute.github.io
  on:
    branch: master
